name: CI Load Test

on:
    pull_request:
        branches:
            - master

jobs:
    ci-load-test:
        runs-on: ubuntu-latest       
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Run vulnerability checks for manifest files
              uses: instrumenta/conftest-action@master
              with:
                files: manifests/
                policy: opa/manifests.rego
            - name: Install tools
              run: sh .github/scripts/install-tools.sh
              env:
                KUBECTL_VERSION: v1.28.2
            - name: Provision kind cluster
              run: sh .github/scripts/provision-cluster.sh