name: CI Load Test

on:
    pull_request:
        branches:
            - master

jobs:
    ci-load-test:
        runs-on: ubuntu-latest       
        steps:
            - name: Checkout code
              uses: actions/checkout@v4